[tools]
"cargo:searchfox-cli" = "latest"
"cargo:treeherder-cli" = "latest"
node = "22"
"npm:web-ext" = "latest"
"pipx:MozPhab" = "latest"
"pipx:mozregression" = "latest"
python = "3.11"
uv = "latest"

[env]
BUILD_BASE = "{{config_root}}"
BUILD_PLATFORM = "{{os()}}"
_.file = "{{config_root}}/.env"
_.path = [
  "{{config_root}}/bin",
  "{{env.HOME}}/.mozbuild/git-cinnabar",
  "{{env.HOME}}/.mozbuild/sccache",
]
_.source = "{{config_root}}/bin/buildenv"
