[tools]
"cargo:searchfox-cli" = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:web-ext" = "latest"
"pipx:MozPhab" = "latest"
"pipx:mozregression" = "latest"
python = "3.11"

[env]
BUILD_BASE = "{{config_root}}"
BUILD_PLATFORM = "{{os()}}"
_.file = "{{config_root}}/.env"
_.path = [
  "{{config_root}}/bin",
  "{{env.HOME}}/.mozbuild/git-cinnabar",
  "{{env.HOME}}/.mozbuild/sccache",
]
_.source = "{{config_root}}/bin/buildenv"
